In [ ]:
import tensorflow as tf

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import numpy as np

In [ ]:
!wget --no-check-certificate \
https: // storage.googleapis.com / learning - datasets / irish - lyrics - eof.txt \
          - O / tmp / irish - lyrics - eof.txt

In [42]:
import urllib.request

url = "https://storage.googleapis.com/learning-datasets/irish-lyrics-eof.txt"
urllib.request.urlretrieve(url, "/tmp/irish-lyrics-eof.txt")

('/tmp/irish-lyrics-eof.txt', <http.client.HTTPMessage at 0x318833010>)

In [ ]:
tokenizer = Tokenizer()

data = open('/tmp/irish-lyrics-eof.txt').read()

corpus = data.lower().split("\n")

tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1

# print(tokenizer.word_index)
# print(total_words)


In [ ]:
total_words

In [ ]:
tokenizer.word_index

In [15]:
corpus[:5]

['come all ye maidens young and fair',
 'and you that are blooming in your prime',
 'always beware and keep your garden fair',
 'let no man steal away your thyme',
 'for thyme it is a precious thing']

In [ ]:
tokenizer.texts_to_sequences(corpus)[: 5]

In [16]:
input_sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i + 1]
        input_sequences.append(n_gram_sequence)

token_list = tokenizer.texts_to_sequences(corpus)
# pad sequences
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

# create predictors and label
xs, labels = input_sequences[:, :-1], input_sequences[:, -1]

ys = tf.keras.utils.to_categorical(labels, num_classes=total_words)

In [21]:
xs.shape

(12038, 15)

In [23]:
labels.shape

(12038,)

In [22]:
ys.shape

(12038, 2690)

In [24]:
input_sequences[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 51, 12],
      dtype=int32)

In [25]:
xs[0]


array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 51],
      dtype=int32)

In [26]:
labels[0]

np.int32(12)

In [30]:
ys

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(12038, 2690))

In [35]:
np.argmax(ys[0])

np.int64(12)

In [39]:
corpus[0]

'come all ye maidens young and fair'

In [40]:
tokenizer.word_index['come']

51

In [41]:
tokenizer.word_index['all']

12

In [ ]:
tokenizer.word_index['ye']

In [ ]:
tokenizer.word_index['maidens']

In [ ]:
tokenizer.word_index['young']

In [ ]:
tokenizer.word_index['and']

In [ ]:
tokenizer.word_index['fair']

In [44]:
tokenizer.word_index['come'], tokenizer.word_index['all']

(51, 12)

In [45]:
xs[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 51],
      dtype=int32)

In [ ]:
np.argmax(ys[0])

In [48]:
tokenizer.word_index['come'], tokenizer.word_index['all'], tokenizer.word_index['ye']

(51, 12, 96)

In [46]:
xs[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 51, 12],
      dtype=int32)

In [47]:
np.argmax(ys[1])

np.int64(96)

In [ ]:
tokenizer.word_index['come'], tokenizer.word_index['all'], tokenizer.word_index['ye'], tokenizer.word_index['maidens']

In [ ]:
xs[2]

In [ ]:
np.argmax(ys[2])

In [ ]:
tokenizer.word_index['come'], tokenizer.word_index['all'], tokenizer.word_index['ye'], tokenizer.word_index['maidens'], tokenizer.word_index['young']

In [ ]:
xs[3]

In [ ]:
np.argmax(ys[2])

In [ ]:
tokenizer.word_index['come'], tokenizer.word_index['all'], tokenizer.word_index['ye'], tokenizer.word_index['maidens'], tokenizer.word_index['young'], tokenizer.word_index['and']

In [ ]:
tokenizer.word_index['come'], tokenizer.word_index['all'], tokenizer.word_index['ye'], tokenizer.word_index['maidens'], tokenizer.word_index['young'], tokenizer.word_index['and']

In [ ]:
tokenizer.word_index['come'], tokenizer.word_index['all'], tokenizer.word_index['ye'], tokenizer.word_index['maidens'], \
tokenizer.word_index['young'], tokenizer.word_index['and'] , tokenizer.word_index['fair']

In [17]:
print(tokenizer.word_index['in'])
print(tokenizer.word_index['the'])
print(tokenizer.word_index['town'])
print(tokenizer.word_index['of'])
print(tokenizer.word_index['athy'])
print(tokenizer.word_index['one'])
print(tokenizer.word_index['jeremy'])
print(tokenizer.word_index['lanigan'])

8
1
71
6
713
39
1790
1791


In [18]:
print(xs[6])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2]


In [19]:
print(ys[6])

[0. 0. 0. ... 0. 0. 0.]


In [20]:
print(xs[5])
print(ys[5])

[   0    0    0    0    0    0    0    0    0   51   12   96 1217   48
    2]
[0. 0. 0. ... 0. 0. 0.]


In [ ]:
print(tokenizer.word_index)

In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len - 1))
model.add(Bidirectional(LSTM(150)))
model.add(Dense(total_words, activation='softmax'))
adam = Adam(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
#earlystop = EarlyStopping(monitor='val_loss', min_delta=0, patience=5, verbose=0, mode='auto')
history = model.fit(xs, ys, epochs=100, verbose=1)
#print model.summary()
print(model)


In [ ]:
import matplotlib.pyplot as plt


def plot_graphs(history, string):
    plt.plot(history.history[string])
    plt.xlabel("Epochs")
    plt.ylabel(string)
    plt.show()

In [ ]:
plot_graphs(history, 'accuracy')


In [49]:
seed_text = "I've got a bad feeling about this"
next_words = 100

for _ in range(next_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len - 1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    seed_text += " " + output_word
print(seed_text)

NameError: name 'model' is not defined